# Generated by Django 5.1.3 on 2024-12-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_parlour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('service_name', models.CharField(max_length=100)),
                ('service_details', models.CharField(max_length=300)),
            ],
        ),
    ]
