# Generated by Django 5.1.3 on 2024-12-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_parlour', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='print',
            field=models.CharField(default=0.0, max_length=10),
            preserve_default=False,
        ),
    ]
