# Generated by Django 5.1.3 on 2024-12-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_parlour', '0003_service_print'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='print',
            new_name='price',
        ),
    ]
