# Generated by Django 5.1.3 on 2024-12-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_parlour', '0004_rename_print_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barber_picture', models.ImageField(upload_to='')),
                ('barber_name', models.CharField(max_length=20)),
                ('barber_profession', models.CharField(max_length=100)),
            ],
        ),
    ]
